## Install dependencies using composer
#FROM composer AS composer
#WORKDIR /app
#COPY . .                    # Note that composer.json and composer.lock are excluded from COPY by the .dockerignore.
#RUN composer install
#
#
#FROM richarvey/nginx-php-fpm  
#RUN apk --no-cache add ca-certificates
#WORKDIR /root/
#COPY --from=0 /go/src/github.com/alexellis/href-counter/app .
#CMD ["./app"]  
#
## Set the working directory within the docker container
#WORKDIR /app
#
## Copy in the app, then install dependencies.
#
## Expose the development server port to the docker service
#EXPOSE 8000