version: "3.7"
services:

  personal_site:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - WEBROOT=/var/www/html/public
    tty: true
    ports:
      - "180:80"
      - "1443:443"

networks:
  default:
    # external:
      # name: reverse_proxy
    name: reverse_proxy