# Install dependencies using composer
FROM composer AS composer
WORKDIR /app
# Note that composer.json and composer.lock are excluded from COPY by the .dockerignore.
COPY . .                    
RUN composer install \
  && php artisan key:generate

# Start the nginx server
FROM richarvey/nginx-php-fpm  
WORKDIR /var/www/html
COPY --from=composer /app .
