version: "3"
services:

  # The Laravel app
  app:
    build: .
    restart: unless-stopped
    tty: true
    ports:
      - "18000:8000" # TODO Create a separate docker-compose.dev.yml file, and move this to it.
    volumes:
      - app:/app

  # The nginx web server
  webserver:
    image: richarvey/nginx-php-fpm
    environment:
      - WEBROOT=/var/www/html/public
    restart: unless-stopped
    tty: true
    ports:
      - "180:80"
      - "1443:443"
    volumes:
      - app:/var/www/html

volumes:
  app: