version: "3"
services:

  # The Laravel app
  app:
    build: .
  #  restart: unless-stopped
    tty: true
    #environment:
    #  SERVICE_NAME: app
    #  SERVICE_TAGS: dev
    #working_dir: /var/www
    networks:
      - app-network
    volumes:
      - public:/app/public

  # The nginx web server
  webserver:
    image: richarvey/nginx-php-fpm
    restart: unless-stopped
    tty: true
    ports:
      - "180:80"
      - "1443:443"
    networks:
      - app-network
    volumes:
      - public:/var/www/html

  ## MySQL server
  #db:
  #  image: mysql:5.7.22
  #  container_name: db
  #  restart: unless-stopped
  #  tty: true
  #  ports:
  #    - "3306:3306"
  #  environment:
  #    MYSQL_DATABASE: laravel
  #    MYSQL_ROOT_PASSWORD: your_mysql_root_password
  #    SERVICE_TAGS: dev
  #    SERVICE_NAME: mysql
  #  #networks:
  #  #  - app-network

volumes:
  public:

# Docker network
networks:
  app-network:
    driver: bridge
