apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name | quote }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: cameronhudson8.com
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: 80
  tls:
    - hosts:
        - cameronhudson8.com
      secretName: tls-cameronhudson8.com
