# Default values for personal-site.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  replicaCount: 2
  image:
    repository: gcr.io/personal-site-249505/github.com/cameronhudson8/personal-site/backend
    tag: latest
    pullPolicy: Always
  livenessProbe:
    initialDelaySeconds: 78
  service:
    type: ClusterIP
    port: 80

# frontend:
#   replicaCount: 2
#   image:
#     repository: gcr.io/personal-site-249505/github.com/cameronhudson8/personal-site/frontend
#     tag: latest
#     pullPolicy: Always
#   containerPort: 
#   service:
#     type: ClusterIP
#     port: 80

test:
  service:
    type: ClusterIP
    port: 80

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: cameronhudson8.com
      paths:
      - path: /
        backend:
          serviceName: backend
          servicePort: 80
      # - path: /
      #   backend:
      #     serviceName: frontend
      #     servicePort: 80
    - host: cameronhudson.info
      paths:
      - path: /
        backend:
          serviceName: backend
          servicePort: 80
      # - path: /
      #   backend:
      #     serviceName: frontend
      #     servicePort: 80
  tls:
  - secretName: tls-cameronhudson8.com
    hosts:
    - cameronhudson8.com
  - secretName: tls-cameronhudson.info
    hosts:
    - cameronhudson.info

# resources: {}
#   # We usually recommend not to specify default resources and to leave this as a conscious
#   # choice for the user. This also increases chances charts run on environments with little
#   # resources, such as Minikube. If you do want to specify resources, uncomment the following
#   # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#   # limits:
#   #   cpu: 100m
#   #   memory: 128Mi
#   # requests:
#   #   cpu: 100m
#   #   memory: 128Mi

# nodeSelector: {}

# tolerations: []

# affinity: {}
