# Default values for personal-site.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  replicaCount: 1
  image:
    repository: docker.io/cameronhudson8/personal-site
    tag: latest
    pullPolicy: Always
  livenessProbe:
    initialDelaySeconds: 78
  service:
    type: ClusterIP
    port: 80

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: cameronhudson8.com
      paths:
      - path: /
        backend:
          serviceName: backend
          servicePort: 80
    - host: cameronhudson.info
      paths:
      - path: /
        backend:
          serviceName: backend
          servicePort: 80
  tls:
  - secretName: tls-cameronhudson8.com
    hosts:
    - cameronhudson8.com
  - secretName: tls-cameronhudson.info
    hosts:
    - cameronhudson.info

resources:
  limits:
    cpu: 0
    memory: 128Mi
  requests:
    cpu: 0
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
